name: Format
on: push
jobs:
    lint:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20.x]
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install deps
          run: npm ci
        - name: Lint
          run: npx eslint ./js/script.js
