name: ESLint

on:
  push:
    branches:
      - dev

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
