name: Format
on: push
jobs:
    lint:
      runs-on: windows-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install deps
          run: npm ci
        - name: Lint
          run: npx eslint ./js/script.js
          